### ISSUE TITLE
Can you add support for accepting the time in EST time zone.

### ISSUE THREAD

**Issue by macadminrohit** [omni-lchen/zabbix-cloudwatch#12]
Currently the script accepts time in UTC as EC2 instance on which the scripts are running in UTC. Our zabbix server is in EST and we want to pass the EST time to the script and get the data from cloudwatch for that particular time. Can you do that?

**Comment by omni-lchen** [comment]
@bsingr has added UTC to local timestamp support, appreciate his contribution. I just amended the script to convert the timestamp when no cloudwatch data received, please re-test the new script, you also need to install python dateutil module.
