### ISSUE TITLE
Wrong values when change timezone

### ISSUE THREAD

**Issue by caiohasouza** [omni-lchen/zabbix-cloudwatch#3]
Hello,

I use timezone BRT (-3), so in file "cron.d/cron.RDS.sh" i change variables "ENDTIME" and "STARTTIME" removing "-u", ex:

ENDTIME=$(date "+%F %H:%M:00")
STARTTIME=$(date "+%F %H:%M:00" -d "5 minutes ago")

In this way the data arrive with timezone correct at my zabbix-server, but this generate problems in values, they not are correct.

How to i can solve this problem?

Thank you

**Comment by omni-lchen** [comment]
You should always use UTC timezone, because cloudwatch uses UTC time, you can change your timezone with this command: ln -s /usr/share/zoneinfo/GMT /etc/localtime

**Comment by caiohasouza** [comment]
Hm Ok, thank you.
