### ISSUE TITLE
Need someexplanation for adding hosts

### ISSUE THREAD

**Issue by dragan1979** [omni-lchen/zabbix-cloudwatch#36]
Can someone explain step 6 Create a new host and linked with the template.

What "new host" means ? is it for example RDS instance or what ?

Thanks in advance

**Comment by dragan979** [comment]
Is this correct way ?

Create host with 0.0.0.0 as interface and link it to the template. Change macros ACCOUNT and REGION to correspond to your case

**Comment by dragan979** [comment]
Does step 6 means:Create host with 0.0.0.0 as interface and link it to the template ?

**Comment by dragan979** [comment]
just found it by browsing other issues:
 "so the port is not required, the host is a dummy host (127.0.0.1) anyway"

**Comment by dragan979** [comment]
just found it by browsing other issues:
 "so the port is not required, the host is a dummy host (127.0.0.1) anyway"
please close

**Comment by dragan1979** [comment]
just found it by browsing other issues:
"so the port is not required, the host is a dummy host (127.0.0.1) anyway"
