### ISSUE TITLE
What is custom multiplier 0.00333333333333333333 for ELB.HTTPCode_Backend_XXX.Sum

### ISSUE THREAD

**Issue by bazaarify** [omni-lchen/zabbix-cloudwatch#50]
Hi

What is custom multiplier 0.00333333333333333333 for ELB.HTTPCode_Backend_XXX.Sum for ?

This might be silly but just curious.

https://github.com/omni-lchen/zabbix-cloudwatch/blob/master/templates/Template_AWS_ELB.xml

Please provide insight.

**Comment by omni-lchen** [comment]
It is just a conversion from requests/5mins to requests/sec, 1/300seconds=0.00333333333333333333

**Comment by bazaarify** [comment]
Ahh! Thanks. As mentioned something silly.
