### ISSUE TITLE
issue with cron.ELB.sh 

### ISSUE THREAD

**Issue by macadminrohit** [omni-lchen/zabbix-cloudwatch#9]
When I run the python script directly it works fine. but when run through the bash(cron.ELB.sh) it throws the error:
[root@ip-10-204-96-207 cron.d]# ./cron.ELB.sh he-dportal-dev-web-elb HL-DirectPortal-Web-ELB zbxserverdev.clouddqt.capitalone.com GR_GG_COF_AWS_COAF_Dev_Developer us-east-1us-east-1
Traceback (most recent call last):
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 415, in <module>
    cw_data = getCloudWatchData(aws_account, aws_region, aws_service, dimensions)
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 198, in getCloudWatchData
    results = cw.get_metric_statistics(period, start_time, end_time, metric_name, namespace, statistics, dimensions)
AttributeError: 'NoneType' object has no attribute 'get_metric_statistics'

**Comment by macadminrohit** [comment]
Fixed.

**Comment by magnetogit** [comment]
How to fix ?
